# Generated by Django 4.2.16 on 2024-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OptionCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_price", models.FloatField()),
                ("strike_price", models.FloatField()),
                (
                    "time_to_maturity",
                    models.FloatField(help_text="Time to maturity in years"),
                ),
                (
                    "risk_free_rate",
                    models.FloatField(help_text="Risk-free rate as percentage"),
                ),
                ("volatility", models.FloatField(help_text="Volatility as percentage")),
                (
                    "option_type",
                    models.CharField(
                        choices=[("call", "Call"), ("put", "Put")], max_length=4
                    ),
                ),
                ("option_price", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
